### ISSUE TITLE
Logic Error in Respawn

### ISSUE THREAD

**Issue by ChrSacher** [thecogdoctor/UnitedOperationsFramework#4]
https://github.com/thecogdoctor/UnitedOperationsFramework/blob/respawn-settings/uo_sys_framework/Core/cfgXEH/init/ServerPreInit.sqf#L126

The DEC and Set needs to be after the call to the cba event.
If you have 1 ticket it gets reduced to 0 and send as 0 to the client, proper behaviour would be to send 1 to the client and then reduce it to 0. 

This needs to be done for all cases.

**Comment by thecogdoctor** [comment]
To clarify, what do you mean by after the call?

After the code in the event is all executed or something else?

**Comment by ChrSacher** [comment]
```
 DEC(_indTicketsRemaining);
                SETVAR(_unit,IndTicketsRemaining,_indTicketsRemaining);
                [QGVAR(PlayerRespawnRecieveTicketEvent), [_unit,true,"IND",_indTicketsRemaining], [_unit]] call CBA_fnc_targetEvent;
```

to 


` 
                [QGVAR(PlayerRespawnRecieveTicketEvent), [_unit,true,"IND",_indTicketsRemaining], [_unit]] call CBA_fnc_targetEvent;
DEC(_indTicketsRemaining);
                SETVAR(_unit,IndTicketsRemaining,_indTicketsRemaining);`

**Comment by ChrSacher** [comment]
NVM this is correct
